name: test_env_xagg_new
channels:
  - conda-forge
dependencies:
  - python=3.8
  ############## These will have to be adjusted to your specific project
  - numpy
  - scipy
  - xarray
  - pandas
  - netcdf4
  - geopandas
  - shapely
  - xesmf
  - matplotlib
  - cartopy
  - cmocean
  ##############
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
